version: "3"
services:
  back:
    image: elster512/bookapiback
    volumes:
      - "data:/app/data"
    ports:
      - 8000:8000
    restart: always
    tty: true
    detach: true
  front:
    depends_on:
      - back
    image: elster512/bookapifront
    ports:
      - 3000:3000
    tty: true
    detach: true
volumes:
  data:
